# fly.toml app configuration file generated for molegario-njs-weather-app-srvr on 2023-11-12T12:00:40-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "molegario-njs-weather-app-srvr"
primary_region = "yul"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
